platform :ios, '9.0'

target 'AcceleratorSample' do
pod 'OTTextChatAccelerator', '1.0.2'
pod 'OTAnnotationKit', '2.0.0-beta2'
pod 'SVProgressHUD'
pod 'OTAcceleratorCore', '1.0.3'
pod 'OpenTok', '2.10.2'
end
