platform :ios, '9.0'

target 'AcceleratorSampleApp-Swift' do
pod 'OTTextChatAccelerator', '1.0.2'
pod 'OTAnnotationAccelerator', '= 1.0.0-beta2'
pod 'SVProgressHUD'
pod 'OTAcceleratorCore', '= 1.1.3'
end
