platform :ios, '9.0'

target 'AcceleratorSampleApp-Swift' do
pod 'OTTextChatAccelerator', '1.0.4'
pod 'OTAnnotationAccelerator', '= 1.0.0-beta2'
pod 'SVProgressHUD', '=2.2.1'
pod 'OTAcceleratorCore', '= 1.1.5'
end
